version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: weekly
    time: "17:00"
    timezone: Europe/London
    
  ignore:
    # ignore all patch updates in dev dependencies.
    # Check github.com/dwyl/technology-stack/issues/126.
    - dependency-name: "ex_doc"
      update-types: ["version-update:semver-patch"]
    - dependency-name: "credo"
      update-types: ["version-update:semver-patch"]
    - dependency-name: "dialyxir"
      update-types: ["version-update:semver-patch"]
    - dependency-name: "excoveralls"
      update-types: ["version-update:semver-patch"]
    - dependency-name: "mock"
      update-types: ["version-update:semver-patch"]
      
